# Generated by Django 3.0.7 on 2021-06-06 17:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_remove_vote_vote_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='vote_value',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
