# Generated by Django 3.0.7 on 2021-06-10 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_auto_20210610_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 6, 10, 23, 53, 55, 381763)),
        ),
        migrations.AlterField(
            model_name='menu',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2021, 6, 10, 23, 53, 55, 381792)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 6, 10, 23, 53, 55, 381763)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2021, 6, 10, 23, 53, 55, 381792)),
        ),
        migrations.AlterField(
            model_name='result',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 6, 10, 23, 53, 55, 381763)),
        ),
        migrations.AlterField(
            model_name='result',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2021, 6, 10, 23, 53, 55, 381792)),
        ),
    ]
