# Generated by Django 3.0.7 on 2021-06-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='employee_type',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Restaurant', 'Restaurant')], default='Employee', max_length=10),
        ),
    ]
