# Generated by Django 3.0.7 on 2021-06-05 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20210605_1046'),
        ('user', '0002_userprofile_employee_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='restaurant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='restaurant.Restaurant'),
        ),
    ]
